5th-contact-session/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

5th-contact-session/learning_logs/urls.py
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

5th-contact-session/multimedia/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

5th-contact-session/users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

5th-contact-session/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    # something learned about a topic
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self) -> str:
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        return self.text

5th-contact-session/users/models.py
from django.db import models

# Create your models here.

5th-contact-session/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

5th-contact-session/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Entry, Topic
from .forms import EntryForm, TopicForm


# Create your views here.
def index(request):
    return render(request, 'learning_logs/index.html')


@login_required
def topics(r):
    topics = Topic.objects.filter(owner=r.user).order_by('date_added')
    context = {'topics': topics}
    # pass
    return render(r, 'learning_logs/topics.html', context)


def topic(r, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != r.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(r, 'learning_logs/topic.html', context)


@login_required
def new_topic(r):
    if r.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=r.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.owner = r.user
            topic.save()
            return redirect('learning_logs:topics')

    context = {'form': form}
    return render(r, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(r, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if r.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=r.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(r, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(r, entry_id):
    # pass
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != r.user:
        raise Http404

    if r.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=r.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(r, 'learning_logs/edit_entry.html', context)

5th-contact-session/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

5th-contact-session/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Learning Log</title>
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a href="{% url 'learning_logs:index' %}" class="navbar-brand">Learning Log</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="{% url 'learning_logs:topics' %}" class="nav-link">Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hello, {{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'users:logout' %}" class="nav-link">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <main class="container" role="main">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}
                {% endblock page_header %}
            </div>
            <div>
                {% block content %}
                {% endblock content %}
            </div>
        </main>
    </body>
</html>

5th-contact-session/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id%}" method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name='submit'>Submit</button>
  </form>
{% endblock content %}

5th-contact-session/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p>Learning logs helps you to keep track of your learning progress</p>
{% endblock content %}

5th-contact-session/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>
    <p>
        Add a new entry:
    </p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <button name='submit'>Add Entry</button>
    </form>
{% endblock content %}

5th-contact-session/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>
        Add a new topic:
    </p>
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Add Topic</button>
    </form>
{% endblock content %}

5th-contact-session/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
  <p>Topic: {{topic}}</p>
  <p><a href="{% url 'learning_logs:new_entry' topic.id%}">Add a New Entry</a></p>
  <p>Entries: </p>
  <ul>
    {% for entry in entries %}
      <li>
        <p>
          {{entry.date_added|date:'M d, Y H:i'}} <a href="{% url 'learning_logs:edit_entry' entry.id%}">Edit</a>
          {{entry.text|linebreaks}}
        </p>
      </li>
    {%empty%}
      <li>No entry added for this topic.</li>
    {% endfor %}
  </ul>
{% endblock content %}

5th-contact-session/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}
  <p>Topics</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a>
      </li>
    {%empty%}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}